apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-app
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: llmops-app
  template:
    metadata:
      labels:
        app: llmops-app
    spec:
      containers:
      - name: llmops-app
        # This image path must equal the one built by CircleCI
        image: us-central1-docker.pkg.dev/gen-lang-client-0729539659/llmops-repo/llmops-app:latest
        ports:
        - containerPort: 5000 # The port the app listens on inside the container
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: llmops-secrets # Kubernetes Secret name
              key: GROQ_API_KEY    # Key inside the Secret

---

apiVersion: v1
kind: Service
metadata:
  name: llmops-service
spec:
  selector:
    app: llmops-app # Selects pods with this label
  ports:
    - protocol: TCP
      port: 80       # Port exposed by the Service (external)
      targetPort: 5000 # Port on the Pod to forward traffic to
  type: LoadBalancer # Exposes the Service externally via a cloud provider's load balancer